name: Build CustomAlbums

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Download Dependencies
      run: |
        wget -O dependencies.zip https://cdn.mdmc.moe/static/cadeps.zip
        unzip dependencies.zip -d dependencies

    - name: Restore and Build
      run: |
        dotnet restore CustomAlbums.sln
        dotnet build "/p:MelonNET6=./dependencies;WORKER=GitHub" CustomAlbums.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomAlbums.dll
        path: ./Output/Debug/CustomAlbums.dll
